[workspace]
members = ["printer", "cli", "formatter"]

[workspace.package]
version = "0.1.2"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
leptosfmt-formatter = { path = "./formatter", version = "0.1.2" }
leptosfmt-pretty-printer = { path = "./printer", version = "0.1.2" }
